apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo-deployment
  labels:
    app: odoo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odoo
  template:
    metadata:
      labels:
        app: odoo
    spec:
      containers:
      - name: odoo
        image: odoo:16.0
        ports:
        - containerPort: 8069
        env:
        - name: HOST
          value: ${DB_ADDR}
        - name: POSTGRES_DB 
          value: odoo
        - name: USER
          value: midpoint
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: mp-secret
              key: password
        volumeMounts:
          - name: odoo-conf
            mountPath: /etc/odoo/
        envFrom:
          - configMapRef:
              name: keycloak-server
      volumes:
        - name: odoo-conf
          configMap:
            name: odoo.conf
            defaultMode: 0555
