apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
  - target:
      kind: Ingress
    patch: |
      - op: remove
        path: /metadata/annotations/kubernetes.io~1ingress.class